"print(\"NAME        AGE     HEIGHT     SCORE\")\n",
"girls = {'1.Evelyn':  '  17         5.5       80',\n",
"          '2.Jessica':  '  16        6.0       85',\n",
"          '3.Somto':  '    17        5.4       70',\n",
"          '4.Edith':   '   18        5.9       60',\n",
"          '5.Liza':     '  16         5.6      76',\n",
"          '6.Madonna':   ' 18          5.5     66',\n",
"          '7.Waje':     ' 17          6.1     87',\n",
"          '9.Tola':     '  20         6.0    95',\n",
"          'Aisha':      '  19         5.7    50',\n",
"          '10.Latifa':   ' 17         5.5    49',\n",
"         }\n",
"for info in girls:\n",
"    print(info, girls [info])"

"print(\"NAME          AGE       HEIGHT     SCORE\")\n",
"boys = {'1.Chinedu':  ' 19      5.7          74',\n",
"        'Liam':      ' 16       5.9          87',\n",
"        'Wale':      ' 18       5.8          75',\n",
"        'Gbenga':    ' 17       6.1          68',\n",
"        'Abiola':    '  20      5.9          66',\n",
"        'Kola':      '  19      5.5          78',\n",
"        'Kunle':      ' 16      6.1          87',\n",
"        'George':     ' 18      5.4          98',\n",
"        'Thomas':     ' 17      5.8          54',\n",
"        'Wesley':     ' 19      5.7          60',\n",
"         }\n",
"for info in boys:\n",
"    print(info, boys [info])"

